apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-api
  template:
    metadata:
      labels:
        app: projects-api
    spec:
      containers:
        - name: projects-api
          image: eviive/repository:projects-api-2.0.0
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: projects-api-env
          volumeMounts:
            - name: logs
              mountPath: /workspace/logs
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: projects-api-logs
      imagePullSecrets:
        - name: projects-image-pull-secret
