apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
#images:
#- name: api
#  newName: eviive/repository
#  newTag: projects-api-2.0.0
helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    version: 0.5.0
    releaseName: projects-api-cnpg-cluster
    namespace: projects-api
    includeCRDs: true
    valuesFile: ../../base/values.cnpg.yaml
